version: "3.8"

services:
  localstack:
    image: localstack/localstack:4.2.0
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,ec2,iam,sts,eks,dynamodb,route53,rds
      - DEBUG=${DEBUG-0}                     
      - DOCKER_HOST=unix:///var/run/docker.sock
    # volumes:
    #   - "${TMPDIR:-/volume}:/var/lib/localstack"
    #   - "/var/run/docker.sock:/var/run/docker.sock"
