---
name: 🚀 Feature Request
description: Suggest an idea or improvement to our product
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: >
        **Thanks :heart: for taking the time to fill out this feature request report!** Please, first try to search to see if a similar issue or if [already exists](https://github.com/jpradoar/event-driven-architecture/issues?q=is%3Aopen+is%3Aissue) for
        your feature.

        we are open to accept any contribution from users or enthusiast. For more info please see
        [here](https://github.com/jpradoar/event-driven-architecture/blob/master/CONTRIBUTING.md).

  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in...
      value: |
         ... Add your feature description here :D 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: >
        Describe the solution you'd like. A clear and concise description of what you want to happen. If you have
        considered alternatives, please describe them.
      value: |
          ... Add your suggested solution description here.
    validations:
      required: false
