name: main-test
on:
  push:
    branches:
      - main

env:
  VULN_SEVERITY: 'CRITICAL'
  
jobs:
  Build-Docker-image:
    runs-on: ubuntu-latest 
    
    steps:
     
    - name: Checkout
      uses: actions/checkout@v3

        
    - name: Run Trivy vulnerability scanner
      id: vulnscan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'domoticz/domoticz:latest'
        hide-progress: true
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: ${{ env.VULN_SEVERITY }}
        #exit-code: '1'              

    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GH_COMMIT_COMMENT_TOKEN }}
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['vulnscan']
          })
