name: main-test
on:
  push:
    branches:
      - main

env:
  REPO_APP: 'noname-file'
  SLACK_CHANNEL: 'builds-and-ci'
  SLACK_MSG_COLOR: '#0092ff'
  BUILD_CONTEXT: './none'
  COMMITER_NAME: 'AutoCommit'
  VULN_SEVERITY: 'CRITICAL,HIGH'
  VULN_TYPE: 'os,library'
  VULN_TIMEOUT_SCAN: '2m0s'
  
jobs:
  Demo-job-test:
    runs-on: ubuntu-latest 
    permissions:
      contents: write # get the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status  
      
    
    steps:
     
    - uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'jpradoar/mqtt-producer:1.1.2'
        output: './vuln_scans/${{ env.REPO_APP }}_vuln_scan.sarif'

    - name: Run Trivy vulnerability scanner
      id: vulnscan
      uses: aquasecurity/trivy-action@master
      with:
        #image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_APP }}:${{ steps.nversion.outputs.NEW_VERSION }}'
        image-ref: 'jpradoar/mqtt-producer:1.1.2'
        vuln-type: ${{ env.VULN_TYPE }}
        severity: ${{ env.VULN_SEVERITY }}
        timeout: ${{ env.VULN_TIMEOUT_SCAN }}
        output: '${{ env.REPO_APP }}_vuln_scan.sarif'
        #exit-code: '1' 

    - name: Upload Trivy scan GH Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: '${{ env.REPO_APP }}_vuln_scan.sarif'
        
    - name: Upload ${{ env.REPO_APP }} vuln scan file
      uses: EndBug/add-and-commit@v9
      with:
        message: 'AutoCommit: Add table file'
        add: '${{ env.REPO_APP }}_vuln_scan.sarif'
