name: main-test
on:
  push:
    branches:
      - main

env:
  REPO_APP: 'none'
  SLACK_CHANNEL: 'builds-and-ci'
  SLACK_MSG_COLOR: '#0092ff'
  BUILD_CONTEXT: './none'
  VULN_OUTPUT_FILE: 'test_vuln_scan'
  COMMITER_NAME: 'AutoCommit'
  VULN_SEVERITY: 'CRITICAL,HIGH'
  VULN_TYPE: 'os,library'
  VULN_TIMEOUT_SCAN: '2m0s'
  
jobs:
  Build-Docker-image:
    runs-on: ubuntu-latest 

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    
    steps:
     
    - uses: actions/checkout@v3

    # You can make whatever type of change to the repo...

    - name: Run Trivy vulnerability scanner
      id: vulnscan
      uses: aquasecurity/trivy-action@master
      with:
        #image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_APP }}:${{ steps.nversion.outputs.NEW_VERSION }}'
        image-ref: 'jpradoar/mqtt-producer:1.1.2'
        format: ${{ env.VULN_FORMAT }}
        vuln-type: ${{ env.VULN_TYPE }}
        severity: ${{ env.VULN_SEVERITY }}
        timeout: ${{ env.VULN_TIMEOUT_SCAN }}
        output: vuln_scans/${{ env.VULN_OUTPUT_FILE }}.sarif     
        #exit-code: '1' 

       
    # ...and then use the action as you would normally do, but providing the path to the repo
    #- uses: EndBug/add-and-commit@v9
    #  with:
    #    message: 'AutoCommit: Add table file'
    #    add: './vuln_scans/${{ env.VULN_OUTPUT_FILE }}.sarif'

     - name: Upload Trivy scan results to GitHub Security tab
       uses: github/codeql-action/upload-sarif@v1
       with:
         sarif_file: './vuln_scans/${{ env.VULN_OUTPUT_FILE }}.sarif'
