name: main-test
on:
  push:
    branches:
      - main

env:
  VULN_SEVERITY: 'CRITICAL'
  
jobs:
  Build-Docker-image:
    runs-on: ubuntu-latest 

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    
    steps:
     
    - uses: actions/checkout@v3

    # You can make whatever type of change to the repo...
    - run: echo "Hello world v2" > ./file.txt

    # ...and then use the action as you would normally do, but providing the path to the repo
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Add the very useful text file'
        add: './file.txt'
