name: main-test
on:
  push:
    branches:
      - main

env:
  REPO_APP: 'noname-file'
  SLACK_CHANNEL: 'builds-and-ci'
  SLACK_MSG_COLOR: '#0092ff'
  BUILD_CONTEXT: './none'
  COMMITER_NAME: 'AutoCommit'
  VULN_SEVERITY: 'CRITICAL,HIGH'
  VULN_TYPE: 'os,library'
  VULN_TIMEOUT_SCAN: '2m0s'
  
jobs:
  Demo-job-test:
    runs-on: ubuntu-latest 
    permissions:
      contents: write # get the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status  
      
    
    steps:
     
    - uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'jpradoar/mqtt-producer:1.1.2'
        format: 'sarif'
        output: 'vuln_scans/asd-trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      #uses: github/codeql-action/upload-sarif@v1
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'vuln_scans/asd-trivy-results.sarif'
