name: main-test
on:
  push:
    branches:
      - main

env:
  VULN_SEVERITY: 'CRITICAL'
  
jobs:
  Build-Docker-image:
    runs-on: ubuntu-latest 

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    
    steps:
     
    #- name: Checkout
    #  uses: actions/checkout@v3

        


    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}


    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: test commit 
