name: python_linter
on:
  push:
    paths:
      - './demo_test/**'
      - '.github/workflows/python_linter.yaml'
  
jobs:
  liner_python_files:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v1
      continue-on-error: true
      with:
         src: "./demo_test/"
         args: "check --output-format full"
