name: vuln_scan
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yaml'
  
jobs:
  Build-Docker-image:
    runs-on: ubuntu-latest 
      
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'repo-vuln.sarif'
          severity: 'CRITICAL'

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'AutoCommit: Add table file'
          add: ./vuln_scans/repo-vuln.sarif
          committer_name: 'AutoCommit'


      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
      #    # Path to SARIF file relative to the root of the repository
      #    sarif_file: results.sarif
      #    # Optional category for the results
      #    # Used to differentiate multiple results for one commit
      #    category: my-analysis-tool

